publishDir: "docs"
enableRobotsTXT: true

baseURL: ""
languageCode: "en-us"
title: "Open GIS LK"
description: "An open-source platform for geospatial data in Sri Lanka."
favicon: "/fav.png"
defaultContentLanguage: en
# theme: open-gis-lk


# outputs:
#   home:
#     - "HTML"
#     - "RSS"
#     - "JSON"
#   page:
#     - "HTML"
#     - "RSS"

# ONLY IN DEV ENV
module:
  mounts:
    - source: "node_modules/bootstrap-icons/font/fonts"
      target: "static/css/fonts"
    - source: "node_modules/bootstrap-icons/font/bootstrap-icons.min.css"
      target: "static/css/bootstrap-icons.min.css"
    # - source: "node_modules/pako/dist/pako.min.js"
    #   target: "static/js/pako.min.js"
    - source: "node_modules/bootstrap-select/dist/css/bootstrap-select.min.css"
      target: "static/css/bootstrap-select.min.css"
    # - source: "node_modules/bootstrap-select/dist/js/bootstrap-select.min.js"
    #   target: "static/js/bootstrap-select.min.js"
    # - source: "node_modules/alasql/dist/alasql.min.js"
    #   target: "static/js/alasql.min.js"
    - source: "static"
      target: "static"




languages:
  si:
    languageCode: si-lk
    contentDir: content/si
    languageName: Sinhala
    weight: 2
    menus:
      main:
      - name: Products
        pageRef: /products
        weight: 10
      - name: Services
        pageRef: /services
        weight: 20
  en:
    languageCode: en-us
    languageName: English
    contentDir: content/en
    weight: 1
    menus:
      main:
      - name: Products
        pageRef: /products
        weight: 10
      - name: Services
        pageRef: /services
        weight: 20

params:
  description: "An open-source platform for geospatial data in Sri Lanka."

  services:
    GoogleAnalytics:
      enable: true
      id: G-5YETP2LVL4
  #   disqus:
  #     shortname: your-disqus-shortname

  author:
    name: "Thiwanka Munasinghe"

  navbar:
    align: "ms-auto" # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Open GIS LK" # Brand name for the brand | default is the title variable
    search:
      enable: true
      placeholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false









# Menus:
#   main:
#     - identifier: blog
#       name: Blog
#       title: Blog posts
#       url: /blogs
#       weight: 1
#     - identifier: gallery
#       name: Gallery
#       title: Blog posts
#       url: /gallery
#       weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2
