publishDir: "docs"
enableRobotsTXT: false

baseURL: ""
languageCode: "en-us"
title: "Open GIS LK"
description: "An open-source platform for geospatial data in Sri Lanka."
favicon: "/fav.png"
defaultContentLanguage: en
# theme: open-gis-lk


# outputs:
#   home:
#     - "HTML"
#     - "RSS"
#     - "JSON"
#   page:
#     - "HTML"
#     - "RSS"

# ONLY IN DEV ENV
module:
  mounts:
    - source: "node_modules/bootstrap-icons/font/fonts"
      target: "static/css/fonts"
    - source: "node_modules/bootstrap-icons/font/bootstrap-icons.min.css"
      target: "static/css/bootstrap-icons.min.css"
    # - source: "node_modules/pako/dist/pako.min.js"
    #   target: "static/js/pako.min.js"
    - source: "node_modules/bootstrap-select/dist/css/bootstrap-select.min.css"
      target: "static/css/bootstrap-select.min.css"
    # - source: "node_modules/bootstrap-select/dist/js/bootstrap-select.min.js"
    #   target: "static/js/bootstrap-select.min.js"
    # - source: "node_modules/alasql/dist/alasql.min.js"
    #   target: "static/js/alasql.min.js"
    - source: "static"
      target: "static"
    - source: "node_modules/papaparse/papaparse.min.js"
      target: "static/js/papaparse.min.js"
    - source: "node_modules/leaflet/dist/leaflet.css"
      target: "static/css/leaflet.css"

languages:
  si:
    languageCode: si-lk
    contentDir: content/si
    languageName: Sinhala
    weight: 2
    menus:
      main:
      - name: Products
        pageRef: /products
        weight: 10
      - name: Services
        pageRef: /services
        weight: 20
  en:
    languageCode: en-us
    languageName: English
    contentDir: content/en
    weight: 1
    menus:
      main:
      - name: Products
        pageRef: /products
        weight: 10
      - name: Services
        pageRef: /services
        weight: 20

# menus content need to be updated in production config as well
params:
  
  dataURL: "http://localhost:8000/getData"
  attributeDataURL: "http://localhost:8000/getAttributeData"

  description: "An open-source platform for geospatial data in Sri Lanka."

  services:
    GoogleAnalytics:
      enable: true
      id: G-5YETP2LVL4

  author:
    name: "Thiwanka Munasinghe"

  navbar:
    align: "ms-auto" # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Open GIS LK" # Brand name for the brand | default is the title variable
    search:
      enable: true
      placeholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false

  menus:
    extents:
      - Name: Admin Boundary
        icon: bi-people-fill
      
      - Name: Tile Number
        icon: bi-people-fill

server:
  headers:
  - for: "/**"
    values:
      Access-Control-Allow-Origin: "*"