publishDir: "docs"
enableRobotsTXT: true

baseURL: ""
languageCode: "en-us"
title: "Open GIS LK"
description: "An open-source platform for geospatial data in Sri Lanka."
favicon: "/fav.png"
defaultContentLanguage: en
# theme: open-gis-lk

# outputs:
#   home:
#     - "HTML"
#     - "RSS"
#     - "JSON"
#   page:
#     - "HTML"
#     - "RSS"

languages:
  si:
    languageCode: si-lk
    contentDir: content/si
    languageName: Sinhala
    weight: 2
    menus:
      main:
        - name: Products
          pageRef: /products
          weight: 10
        - name: Services
          pageRef: /services
          weight: 20
  en:
    languageCode: en-us
    languageName: English
    contentDir: content/en
    weight: 1
    menus:
      main:
        - name: Products
          pageRef: /products
          weight: 10
        - name: Services
          pageRef: /services
          weight: 20

params:
  dataURL: "https://opengislk.alwaysdata.net/getData"
  attributeDataURL: "https://opengislk.alwaysdata.net/getAttributeData"

  description: "An open-source platform for geospatial data in Sri Lanka."

  services:
    GoogleAnalytics:
      enable: true
      id: G-5YETP2LVL4
  #   disqus:
  #     shortname: your-disqus-shortname

  author:
    name: "Thiwanka Munasinghe"

  navbar:
    align: "ms-auto" # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Open GIS LK" # Brand name for the brand | default is the title variable
    search:
      enable: true
      placeholder: "Search"
    stickyNavBar:
      enable: true
      showOnScrollUp: true
    enableSeparator: false

  menus:
    products:
      # - Name: Electricity
      #   icon: bi-plug-fill
      #   datasets:
      #     - id: dataset-outage
      #       name: Outages
      #       description: Current electricity outages
      # - Name: Agriculture
      #   icon: bi-leaf-fill
      #   datasets:
      #     - id: dataset-cereal-production-2012-yala
      #       name: Cereal Production 2012
      #       description: Cereal Production Statistics - Yala Season 2012
      - Name: Demographic
        icon: bi-people-fill
        datasets:
          - id: gender-by-gnd-latest
            aoi_type: name
            level: 4
            name: Gender Distribution by GND
            description: "Gender breakdown from latest data, aggregated by Grama Niladhari Division (GND). Includes counts of male, female, and total population per GND."
